### ISSUE TITLE
enabling dummy-form-filler breaks xml display

### ISSUE THREAD

**Issue by DeveloperChris** [ptomaszek/dummy-form-filler#20] opened 2017-09-18 23:28 UTC
When enabled dummy form filler breaks the display of well formed XML.

So This
![image](https://user-images.githubusercontent.com/212806/30569170-702bfa2a-9d18-11e7-92c5-3ff8bf61e6d4.png)

Becomes This
![image](https://user-images.githubusercontent.com/212806/30569179-7c595e14-9d18-11e7-9e0f-aba75bfc33fa.png)

The only action needed to corrupt the display is enabling the plugin.

Once disabled the page needs to be loaded again to see the correctly formed XML

Use this feed as an example
https://tatts.com/pagedata/racing/2011/10/5/RaceDay.xml

the above page just shows a blank screen when the extension is enabled

**Comment by ptomaszek** [comment] 2017-09-19 18:31
Indeed this happens in Firefox, yet works fine in Chrome.

Thanks for the finding, I'll see what's going on and let you know when a fix is ready.

PS I can only imagine how frustrating it was for you to face such weirdness. Hope it didn't take too long to find the one to blame

**Comment by DeveloperChris** [comment] 2017-09-20 00:39
Once I realised it was a plugin I disabled all and re-enabled 4 at a time. (I have a few, some were already disable [thanks FF :( ]) the weird thing was after enabling my extensions it was still OK. 

Maybe there was a configuration error?

Thought I had better count the number of re-enabled extensions and compare it to the list I created before hand. Oops the only one I had forgotten to re-enable was dummy form filler. Voila the problem came back. So it was the last one I checked. Of Course...

**Comment by ptomaszek** [comment] 2017-09-23 10:31
The issue is fixed in version 1.2.3 (should be soon available on https://addons.mozilla.org/pl/firefox/addon/dummy-form-filler/). 

What was the problem? jQuery, apparently. Why was the library causing the issue? I couldn't find out. Also, as I couldn't resign from jQuery, I turned off the plugin for pages ending with `.xml`. 

I know it's just a workaround rather than a proper fix.

**Closed by ptomaszek** 2017-09-23 10:31 UTC
